# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  snapshot_stats:
    class: SnapshotStatsJob
    queue: default
    schedule: at 1am every day
  
  track_daily_views:
    class: TrackDailyViewsJob
    queue: default
    schedule: at 2am every day
  
  fetch_real_youtube_stats:
    class: FetchRealYoutubeStatsJob
    queue: default
    schedule: at 3am every day
  
  cleanup_posthog_recordings:
    class: ManagePosthogRecordingsJob
    queue: default
    args: []
    schedule: every 6 hours

development:
  snapshot_stats:
    class: SnapshotStatsJob
    queue: default
    schedule: at 1am every day
  
  track_daily_views:
    class: TrackDailyViewsJob
    queue: default
    schedule: at 2am every day
  
  fetch_real_youtube_stats:
    class: FetchRealYoutubeStatsJob
    queue: default
    schedule: at 3am every day
  
  cleanup_posthog_recordings:
    class: ManagePosthogRecordingsJob
    queue: default
    args: []
    schedule: every 6 hours
